namespace NSpark.Signer;

/// <summary>
/// A FROST signing-round commitment (hiding + binding nonce commitments).
/// Used both for the user's commitment and for each Signing Operator's commitment.
/// </summary>
/// <param name="Hiding">33-byte compressed secp256k1 point — the hiding nonce commitment.</param>
/// <param name="Binding">33-byte compressed secp256k1 point — the binding nonce commitment.</param>
public sealed record SigningCommitment(byte[] Hiding, byte[] Binding);

/// <summary>
/// A single verifiable secret-sharing share with its accompanying public proofs.
/// Returned by <see cref="ISparkSigner"/> methods that split private material across SOs.
/// The share itself is sensitive; the proofs are public commitments.
/// </summary>
/// <param name="Index">1-based share index assigned by VSS (matches an SO via <c>operator.Index + 1</c>).</param>
/// <param name="Share">32-byte scalar — the SO-bound share. Sensitive.</param>
/// <param name="Proofs">Public commitments verifying the share is consistent with the others.</param>
public sealed record FrostVssShare(uint Index, byte[] Share, IReadOnlyList<byte[]> Proofs);

/// <summary>
/// One-shot result of FROST signing for a leaf: the leaf's public key, the user-side
/// nonce commitment (already shared with SOs implicitly via the returned signature),
/// and the partial signature ready for aggregation with SO partials.
/// </summary>
/// <param name="PublicKey">33-byte compressed public key for the leaf's signing key.</param>
/// <param name="Commitment">The user's FROST commitment that was used in this signing round.</param>
/// <param name="UserSignature">The user's partial signature.</param>
public sealed record LeafFrostSignature(
    byte[] PublicKey,
    SigningCommitment Commitment,
    byte[] UserSignature);

/// <summary>
/// First phase of a two-phase FROST signing flow: the commitment is published to SOs
/// alongside the signing request, and the opaque <see cref="NonceHandle"/> is held by
/// the caller until the corresponding <see cref="ISparkSigner.SignLeafFrostWithNonceAsync"/>
/// call. The nonce handle is opaque to the wallet — the default in-process signer puts
/// the secret nonce bytes inside; a remote signer can use any blob the service understands.
/// </summary>
public sealed record LeafFrostNonceCommitment(
    byte[] PublicKey,
    SigningCommitment Commitment,
    byte[] NonceHandle);

/// <summary>
/// Result of computing tweak shares for a send-side leaf transfer.
/// </summary>
/// <param name="SecretCipher">ECIES-encrypted "new" intermediate signing key, addressed to the receiver.</param>
/// <param name="NewPublicKey">33-byte compressed public key derived from the new intermediate signing key.</param>
/// <param name="Shares">Per-SO VSS shares of <c>(oldLeafKey - newKey)</c> with proofs.</param>
public sealed record LeafTweakSharesResult(
    byte[] SecretCipher,
    byte[] NewPublicKey,
    IReadOnlyList<FrostVssShare> Shares);

/// <summary>
/// Result of computing tweak shares for a receive-side claim. The signer decrypts the
/// sender's <paramref name="senderSecretCipher"/> internally to obtain the sender's
/// intermediate signing key, derives the receiver's new per-leaf key, and splits the
/// difference among SOs.
/// </summary>
/// <param name="NewPublicKey">33-byte compressed public key of the receiver's new per-leaf signing key.</param>
/// <param name="Shares">Per-SO VSS shares of <c>(senderIntermediate - newLeafKey)</c> with proofs.</param>
public sealed record ClaimTweakSharesResult(
    byte[] NewPublicKey,
    IReadOnlyList<FrostVssShare> Shares);

/// <summary>
/// Result of generating and VSS-splitting a Lightning HTLC preimage. The preimage itself
/// never leaves the signer — only its SHA-256 (payment hash) and the per-SO shares.
/// </summary>
/// <param name="PaymentHash">SHA-256 of the preimage — the BOLT11 <c>payment_hash</c>.</param>
/// <param name="Shares">Per-SO VSS shares of the preimage with proofs.</param>
public sealed record PreimageShareSplitResult(
    byte[] PaymentHash,
    IReadOnlyList<FrostVssShare> Shares);

/// <summary>
/// An ephemeral adaptor key generated by the signer for use in atomic swaps.
/// The wallet only ever sees the public key; the private half stays inside the signer
/// behind the opaque <see cref="Handle"/>.
/// </summary>
/// <param name="PublicKey">33-byte compressed public key of the adaptor.</param>
/// <param name="Handle">Opaque handle the signer uses to identify the adaptor secret later.</param>
public sealed record AdaptorKeyHandle(byte[] PublicKey, byte[] Handle);
