namespace NSpark.Signer;

/// <summary>
/// A FROST signing-round commitment (hiding + binding nonce commitments).
/// Used both for the user's commitment and for each Signing Operator's commitment.
/// </summary>
/// <param name="Hiding">33-byte compressed secp256k1 point — the hiding nonce commitment.</param>
/// <param name="Binding">33-byte compressed secp256k1 point — the binding nonce commitment.</param>
public sealed record SigningCommitment(byte[] Hiding, byte[] Binding);

/// <summary>
/// One-shot result of FROST signing for a leaf: the leaf's public key, the user-side
/// nonce commitment (already shared with SOs implicitly via the returned signature),
/// and the partial signature ready for aggregation with SO partials.
/// </summary>
/// <param name="PublicKey">33-byte compressed public key for the leaf's signing key.</param>
/// <param name="Commitment">The user's FROST commitment that was used in this signing round.</param>
/// <param name="UserSignature">The user's partial signature.</param>
public sealed record LeafFrostSignature(
    byte[] PublicKey,
    SigningCommitment Commitment,
    byte[] UserSignature);

/// <summary>
/// First phase of a two-phase FROST signing flow: the commitment is published to SOs
/// alongside the signing request, and the opaque <see cref="NonceHandle"/> is held by
/// the caller until the corresponding <see cref="ISparkSigner.SignLeafFrostWithNonceAsync"/>
/// call. The nonce handle is opaque to the wallet — the default in-process signer puts
/// the secret nonce bytes inside; a remote signer can use any blob the service understands.
/// </summary>
public sealed record LeafFrostNonceCommitment(
    byte[] PublicKey,
    SigningCommitment Commitment,
    byte[] NonceHandle);

/// <summary>
/// An ephemeral adaptor key generated by the signer for use in atomic swaps.
/// The wallet only ever sees the public key; the private half stays inside the signer
/// behind the opaque <see cref="Handle"/>.
/// </summary>
/// <param name="PublicKey">33-byte compressed public key of the adaptor.</param>
/// <param name="Handle">Opaque handle the signer uses to identify the adaptor secret later.</param>
public sealed record AdaptorKeyHandle(byte[] PublicKey, byte[] Handle);

/// <summary>
/// Identifies one Signing Operator as a target for an ECIES-encrypted share bundle.
/// The signer uses <see cref="IdentityPublicKey"/> to ECIES-encrypt the SO's payload and
/// <see cref="ShareIndex"/> to pick which VSS share goes to that SO. <see cref="SoId"/> is
/// echoed back in the result map so the wallet can plug the encrypted blobs into the
/// corresponding gRPC request fields.
/// </summary>
/// <param name="SoId">SO identifier string used as the map key in the wire protocol.</param>
/// <param name="ShareIndex">1-based VSS share index for this SO (matches <c>SigningOperatorInfo.Index + 1</c>).</param>
/// <param name="IdentityPublicKey">33-byte compressed identity public key of the SO.</param>
public sealed record SoTarget(string SoId, uint ShareIndex, byte[] IdentityPublicKey);

/// <summary>
/// One leaf's contribution to a send-side tweak batch (transfer / Lightning send / swap /
/// cooperative-exit withdrawal). The signer derives the leaf's current signing key, picks
/// a fresh intermediate key, computes the tweak, ECIES-encrypts the intermediate key to
/// <see cref="ReceiverPublicKey"/>, signs the tweak signature payload, and folds everything
/// into the per-SO encrypted package.
/// </summary>
public sealed record SendTweakLeafDescriptor(string LeafId, byte[] ReceiverPublicKey);

/// <summary>
/// Result of <see cref="ISparkSigner.BuildEncryptedSendTweaksAsync"/>: one ECIES-encrypted
/// <c>SendLeafKeyTweaks</c> proto per SO, keyed by SO id. The wallet plugs each blob into
/// the <c>key_tweak_package</c> map of the outgoing request — no plaintext share material
/// ever crosses the wallet boundary.
/// </summary>
public sealed record EncryptedSendTweakBatch(
    IReadOnlyDictionary<string, byte[]> EncryptedPackageBySoId);

/// <summary>
/// One leaf's contribution to a claim-side tweak batch. The signer ECIES-decrypts
/// <see cref="SenderSecretCipher"/> internally to obtain the sender's intermediate
/// signing key, derives the receiver's new per-leaf key, computes the tweak, and folds
/// everything into the per-SO encrypted package.
/// </summary>
public sealed record ClaimTweakLeafDescriptor(string LeafId, byte[] SenderSecretCipher);

/// <summary>
/// Result of <see cref="ISparkSigner.BuildEncryptedClaimTweaksAsync"/>: per-leaf new
/// public keys (which the wallet uses as the receiving key in claim refund txs) plus one
/// ECIES-encrypted <c>ClaimLeafKeyTweaks</c> proto per SO.
/// </summary>
public sealed record EncryptedClaimTweakBatch(
    IReadOnlyDictionary<string, byte[]> NewPublicKeyByLeafId,
    IReadOnlyDictionary<string, byte[]> EncryptedPackageBySoId);

/// <summary>
/// Result of <see cref="ISparkSigner.BuildEncryptedPreimageSharesAsync"/>: the BOLT11
/// payment hash plus one ECIES-encrypted <c>SecretShare</c> proto per SO. The preimage
/// itself never leaves the signer.
/// </summary>
public sealed record EncryptedPreimageShareBundle(
    byte[] PaymentHash,
    IReadOnlyDictionary<string, byte[]> EncryptedShareBySoId);
